from werkzeug.security import check_password_hash, generate_password_hash
from App.database import db

class Player(db.Model):


    id = db.Column(db.Integer, primary_key=True)
    player_id = db.Column(db.Integer, unique=True, nullable=False)
    name = db.Column(db.String(1000))
    full_name = db.Column(db.String(1000))
    height_cm = db.Column(db.Integer)
    weight_kg = db.Column(db.Integer)
    dob = db.Column(db.Date)
    preferred_foot = db.Column(db.String(100))
    body_type = db.Column(db.String(500))
    club_id = db.Column(db.Integer)
    club_name = db.Column(db.String(1000))
    club_league_id = db.Column(db.Integer)
    club_league_name = db.Column(db.String(1000))
    

    crossing = db.Column(db.Integer)
    finishing = db.Column(db.Integer)
    heading_accuracy = db.Column(db.Integer)
    short_passing = db.Column(db.Integer)
    volleys = db.Column(db.Integer)
    dribbling = db.Column(db.Integer)
    curve = db.Column(db.Integer)
    fk_accuracy = db.Column(db.Integer)
    long_passing = db.Column(db.Integer)
    ball_control = db.Column(db.Integer)
    acceleration = db.Column(db.Integer)
    sprint_speed = db.Column(db.Integer)
    agility = db.Column(db.Integer)
    reactions = db.Column(db.Integer)
    balance = db.Column(db.Integer)
    shot_power = db.Column(db.Integer)
    jumping = db.Column(db.Integer)
    stamina = db.Column(db.Integer)
    strength = db.Column(db.Integer)
    long_shots = db.Column(db.Integer)
    aggression = db.Column(db.Integer)
    interceptions = db.Column(db.Integer)
    positioning = db.Column(db.Integer)
    vision = db.Column(db.Integer)
    penalties = db.Column(db.Integer)
    composure = db.Column(db.Integer)
    defensive_awareness = db.Column(db.Integer)
    standing_tackle = db.Column(db.Integer)
    sliding_tackle = db.Column(db.Integer)
    gk_diving = db.Column(db.Integer)
    gk_handling = db.Column(db.Integer)
    gk_kicking = db.Column(db.Integer)
    gk_positioning = db.Column(db.Integer)
    gk_reflexes = db.Column(db.Integer)
    

    season = db.Column(db.String(1000))
    club_nation = db.Column(db.String(1000))
    career_length = db.Column(db.Integer)
    start_year_final = db.Column(db.Integer)
    end_recent_year_final = db.Column(db.Integer)

    position_groups = db.Column(db.String(1000))


    cam = db.Column(db.Integer)
    cb = db.Column(db.Integer)
    cdm = db.Column(db.Integer)
    cf = db.Column(db.Integer)
    cm = db.Column(db.Integer)
    gk = db.Column(db.Integer)
    lb = db.Column(db.Integer)
    lm = db.Column(db.Integer)
    lw = db.Column(db.Integer)
    lwb = db.Column(db.Integer)
    rb = db.Column(db.Integer)
    rm = db.Column(db.Integer)
    rw = db.Column(db.Integer)
    rwb = db.Column(db.Integer)
    st = db.Column(db.Integer)
    
    age = db.Column(db.Integer)


    nation = db.Column(db.String(1000))
    league = db.Column(db.String(1000))
    preferred_foot_left = db.Column(db.Integer)
    preferred_foot_right = db.Column(db.Integer)

    speed_strength_ratio=db.Column(db.Float)
    agility_height_ratio=db.Column(db.Float)
    jumping_height_ratio=db.Column(db.Float)
    stamina_weight_ratio=db.Column(db.Float)
    offensive_skills=db.Column(db.Float)
    defensive_skills=db.Column(db.Float)
    playmaking_skills=db.Column(db.Float)
    physical_dominance=db.Column(db.Float)
    technical_ability=db.Column(db.Float)
    speed_composite=db.Column(db.Float)
    goalkeeper_skills=db.Column(db.Float)
    offensive_defensive_diff=db.Column(db.Float)
    offensive_defensive_ratio=db.Column(db.Float)
    technical_physical_ratio=db.Column(db.Float)
    pressure_handling =db.Column(db.Float)
